In [1]:
import pandas as pd
import os
import matplotlib

In [4]:
matched_trades = pd.read_csv('../temporary/matched_trades.csv', parse_dates = ['date'], infer_datetime_format = True)
matched_trades

,date,tid,price,amount,Currency,counter,tid2,date2,amount2,Currency2,time_diff
0,2017-03-15 00:00:24,6277292,1068.00,0.110000,GBP,1,100294.0,2017-03-15 00:16:23,0.110000,VEF,0 days 00:15:59
1,2017-03-15 00:00:40,6277296,1062.93,0.117600,GBP,1,100435.0,2017-03-15 03:40:44,0.117600,VEF,0 days 03:40:04
2,2017-03-15 00:00:49,6277295,547460.29,0.159900,NGN,1,6277321.0,2017-03-15 00:01:37,0.159900,USD,0 days 00:00:48
3,2017-03-15 00:00:58,6277291,1526.72,0.039300,USD,1,6277338.0,2017-03-15 00:06:06,0.039300,USD,0 days 00:05:08
4,2017-03-15 00:01:14,6277315,78740.16,0.012700,RUB,1,6277362.0,2017-03-15 00:12:30,0.012700,RUB,0 days 00:11:16
...,...,...,...,...,...,...,...,...,...,...,...
4883248,2022-09-27 22:44:19,56510120,84277182.39,0.001083,COP,1,56510151.0,2022-09-27 22:52:11,0.001083,COP,0 days 00:07:52
4883249,2022-09-27 23:28:04,56510220,158900.00,0.002000,VED,1,56510533.0,2022-09-28 01:42:17,0.002000,CRC,0 days 02:14:13
4883250,2022-09-27 23:46:13,56510295,1227596.37,0.000407,RUB,1,56510426.0,2022-09-28 00:46:25,0.000407,RUB,0 days 01:00:12
4883251,2022-09-28 00:10:07,56510348,19417017.91,0.007210,CLP,1,56510346.0,2022-09-28 00:13:07,0.007210,CLP,0 days 00:03:00
4883252,2022-09-28 00:55:32,56510444,423109.39,0.004727,MXN,1,56510500.0,2022-09-28 01:24:00,0.004727,COP,0 days 00:28:28

In [ ]:
def plot_series(data, currency_from, currency_to, date_from, date_to):